WebdevProjectStarterTemplate/Pages/Rest/Alles betalen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebdevProjectStarterTemplate.Models;
using WebdevProjectStarterTemplate.Repositories;

namespace WebdevProjectStarterTemplate.Pages.Rest
{
    public class Alles_betalenModel : PageModel
    {
        public int RTableId { get; set; }
        public List<OrderLine> orders = new();
        string userid;

        public IActionResult OnGet()
        {
            userid = HttpContext.Session.GetString("userID");
            if (userid == null)
            {
                return new RedirectResult("../login");
            }

            RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
            orders = new OrderRepo().GetOrders(RTableId);
            return Page();
        }
        public IActionResult OnPost()
        {
            RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);

            orders = new OrderRepo().GetOrders(RTableId);

            foreach (var order in orders)
            {
                order.RTableId = RTableId;
                order.AmountPaid = order.Amount;
                new OrderRepo().BetaalAlles(order);
            }
            return new RedirectResult("Alles betalen");
        }
    }
}

WebdevProjectStarterTemplate/Pages/Rest/Bestellen.cshtml.cs
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections;
using WebdevProjectStarterTemplate.Models;
using WebdevProjectStarterTemplate.Repositories;

namespace WebdevProjectStarterTemplate.Pages;

[BindProperties]
public class BestellenModel : PageModel
{
    public OrderLine order = new();
    public IEnumerable<Category> CategoriesWithProduct { get; set; }
    public string categorie;
    string userid;

    public IActionResult OnGet()
    {
        userid = HttpContext.Session.GetString("userID");
        if (userid == null)
        {
            return new RedirectResult("../login");
        }

        order.RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
        CategoriesWithProduct = new CategoryRepository().GetCategoriesWithProducts();
        return Page();
    }
    public IActionResult OnPost()
    {
        order.RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
        int iterator = 1;
        var rows = Request.Form;
        foreach (var row in rows)
        {
            if (row.Key.Equals("__RequestVerificationToken"))
            {
                break;
            }
            if (iterator % 2 == 1)
            {
                order.ProductId = Convert.ToInt32(row.Value);
            }

            else
            {
                order.Amount = Convert.ToInt32(row.Value);
                try
                {
                    new OrderRepo().AddOrder(order);
                } catch { continue; } //TODO inplaats van continue, een orderUpdate()
            }
            iterator++;
        }
        //omdat het formulier dynamisch is aangemaakt doorloopt hij de request.form
        //uiteindelijk komt er een request verification of zoiets en die wordt gefilterd
        return Redirect("/Rest/Overzicht");
    }
}

WebdevProjectStarterTemplate/Pages/Rest/Overzicht.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using WebdevProjectStarterTemplate.Models;
using WebdevProjectStarterTemplate.Repositories;

namespace WebdevProjectStarterTemplate.Pages.Rest
{
    public class OverzichtModel : PageModel
    {
        public List<OrderLine> orders = new();
        public int RTableId { get; set; }
        public OrderLine neworder { get; set; } = new();
        string userid;

        public IActionResult OnGet()
        {
            userid = HttpContext.Session.GetString("userID");
            if (userid == null)
            {
                return new RedirectResult("../login");
            }

            RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);

            orders = new OrderRepo().GetOrders(RTableId);
            return Page();


        }
        public IActionResult OnPostIncrement() 
        {
            neworder.Amount = Convert.ToInt32(Request.Form["Amount"]);
            neworder.ProductId = Convert.ToInt32(Request.Form["ProductId"]);

            neworder.RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
            neworder.Amount++;
            new OrderRepo().UpdateOrder(neworder);
            return new RedirectResult(" Overzicht");
        }
        public IActionResult OnPostDecrement()
        {
            neworder.Amount = Convert.ToInt32(Request.Form["Amount"]);
            if (neworder.Amount > 0)
            {
                neworder.ProductId = Convert.ToInt32(Request.Form["ProductId"]);
                neworder.RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
                neworder.Amount--;
                new OrderRepo().UpdateOrder(neworder);
            }
            if (neworder.Amount == 0)
            {
                //TODO: remove row
                neworder.ProductId = 0;
                neworder.RTableId = 0;
                orders.Remove(neworder);
                new OrderRepo().UpdateOrder(neworder);
            }

            return new RedirectResult("Overzicht");
        }
    }
}

WebdevProjectStarterTemplate/Pages/Rest/Per persoon betalen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebdevProjectStarterTemplate.Models;
using WebdevProjectStarterTemplate.Repositories;

namespace WebdevProjectStarterTemplate.Pages.Rest
{
    public class Per_persoon_betalenModel : PageModel
    {
        public int RTableId { get; set; }
        public List<OrderLine> orders = new();
        public OrderLine order { get; set; } = new();
        string userid;

        public IActionResult OnGet()
        {
            RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
            orders = new OrderRepo().GetOrders(RTableId);
            userid = HttpContext.Session.GetString("userID");
            if (userid == null)
            {
                return new RedirectResult("../login");
            }
            return Page();

        }
        public IActionResult OnPost()
        {
            order.RTableId = Convert.ToInt32(Request.Cookies["RTableId"]);
            int iterator = 1;
            var rows = Request.Form;
            foreach(var row in rows)
            {
                if (row.Key.Equals("__RequestVerificationToken"))
                {
                    break;
                }
                if (iterator % 2 == 1)
                {
                    order.AmountPaid= Convert.ToInt32(row.Value);
                }


                if (iterator % 2 == 0)
                {
                    order.ProductId= Convert.ToInt32(row.Value);
                    new OrderRepo().Betaal(order);
                }
                iterator++;
            }
            return new RedirectResult("Alles betalen");
        }
    }
}

WebdevProjectStarterTemplate/Pages/Rest/Alles betalen.cshtml
@page
@model WebdevProjectStarterTemplate.Pages.Rest.Alles_betalenModel
@{
}
<h1><b>Rekening</b></h1>
<p>De rekening voor tafel: <a style="font-weight: bold">@Model.RTableId</a></p>
<form method="post">
<table class="table table-striped">
    <thead>
        <tr>
            <td><b>Product</b></td>
            <td><b>Betaald</b></td>
            <td><b>Prijs per stuk</b></td>
            <td><b>Totaal</b></td>
        </tr>
    </thead>
    <tbody>
        @{
            decimal alles = 0;
            foreach (var order in Model.orders)
            {
                alles += order.Total;
                <tr>
                    <td>@order.Name</td>
                    <td>@order.AmountPaid van de @order.Amount</td>
                    <td>@order.Price</td>
                    <td>@order.Total</td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><b>@alles</b></td>
        </tr>
    </tfoot>
</table>
    <button class="btn btn-danger">Betaal</button>
    <a class="btn btn-secondary" asp-area="" asp-page="/Rest/Per persoon betalen">Per persoon betalen</a>
</form>

WebdevProjectStarterTemplate/Pages/Rest/Bestellen.cshtml
@page
@model WebdevProjectStarterTemplate.Pages.BestellenModel
@{
}
<h1><b>Bestellen</b></h1>
<p>Deze bestelling is voor tafel: <a style="font-weight: bold">@Model.order.RTableId</a></p>

<div class="container">
    <div class="row">
        <div class="col">
            
            @* Alle typen dranken in een lijstje printen op de pagina *@
            <p style="font-weight: bold; margin-bottom: 10px">Type drank</p>
            <table class="table table-striped">
                <thead>
                </thead>
                <tbody>

                    @foreach (var category in @Model.CategoriesWithProduct)
                    {
                        <tr>
                            <td><button type="submit" class="btn btn-outline-dark" onclick="showCategory('@category.Name')">@category.Name</button></td>
                        </tr>
                    }
                </tbody>
            </table>
            
            
        </div>
        <div class="col">
            @* Alles wat onder het type drank valt *@
            <div class="d-flex justify-content-between" style="margin-bottom: -5px">
                <p style="font-weight: bold; margin-bottom: 10px" class="col-1">Soorten</p>
                <p style="font-weight: bold" class=" col-4">Prijs</p>
            </div>
            <div class="d-flex">
                <table class="table table-striped">
                    <thead>
                    </thead>
                    <tbody>
                    @foreach (var category in @Model.CategoriesWithProduct){
                        foreach (var product in category.Products){
                            <tr class="productsview @category.Name justify-content-between">
                                <td class="p-2 flex-fill bd-highlight">
                                    @product.Name
                                </td>
                                <td class="p-2 align-items-end">
                                    €@product.Price,-
                                </td>
                                <td class="align-items-end">
                                        <button class="btn btn-primary rounded-circle btn-sm row-cols-sm-1" onclick="addRow('@product.Name', '@product.ProductId')" style="font-weight: bold">+</button>
                                </td>
                            </tr>
                        }
                    }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-6">
            <p style="font-weight: bold; margin-bottom: 10px">Bestelling</p>
            <form method="post")>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td><b>Product</b></td>
                        <td><b>Aantal</b></td>
                    </tr>
                </thead>
                <tbody id="ordertable">

                </tbody>
                <tfoot>
                    <tr>
                        <td> <button type="submit" class="btn btn-primary" style="margin-top: 10px">Versturen</button></td>                       
                    </tr>
                </tfoot>
            </table>
            </form>
        </div>

    </div>
</div>
<script>

    
    function addRow(product, id){
        var element = document.getElementById(id)
        if (!element) {
        var newRow = document.createElement("tr");
        newRow.id = id;
            newRow.innerHTML = `<td>${product}</td>
            <td><button type="button" class="btn btn-dark rounded-circle btn-sm" style="font-weight: bold" onclick="decreaseAmount(${id})">-</button><a id ="amount${id}"style="margin: 5px">1</a><button type="button" class="btn btn-dark rounded-circle btn-sm" style="font-weight: bold" onclick="increaseAmount(${id})">+</button><input type="hidden" name="orderid${id}" value="${id}"> <input id ="order${id}" type="hidden" name="orderamount${id}" value="1"></td>`;

            
            
            document.getElementById("ordertable").appendChild(newRow);
        }
        else {
            increaseAmount(id);
        }
    }
    function hideAllProducts(){
        var elements = document.getElementsByClassName("productsview");
        for (var i = 0; i < elements.length; i++) {
            elements[i].style.display = "none";
        }
    }
    function showCategory(id){
        hideAllProducts();
        var elements = document.getElementsByClassName(id)
        for (var i = 0; i < elements.length; i++) {
            elements[i].style.display = "flex";
        }
    }
    function increaseAmount(id){
        var amountid = `amount${ id }`
        var newid = `order${id}`;
        var element = document.getElementById(newid)
        element.value = Number(element.value) +1

        var element = document.getElementById(amountid)
        element.innerHTML = Number(element.innerHTML) +1
    }
    function decreaseAmount(id){
        var amountid = `amount${id}`
        var newid = `order${id}`;
        var element = document.getElementById(newid)
        if (element.value < 2){
            element.parentElement.parentElement.remove();
        }
        else {
        element.value = Number(element.value) - 1

        var element = document.getElementById(amountid)
        element.innerHTML = Number(element.innerHTML) - 1
        }
    }
    function deleteOrder(id){
        hideAllProducts();
    }
    showCategory(' Bier');

</script>

WebdevProjectStarterTemplate/Pages/Rest/Overzicht.cshtml
@page
@model WebdevProjectStarterTemplate.Pages.Rest.OverzichtModel
@{
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h1><b>Overzicht</b></h1>
<p>De geselecteerde tafel is <a style="font-weight: bold">@Model.RTableId</a></p>
<table class="table table-striped">
    <thead>
        <tr>
            <td><b>Product</b></td>
            <td><b>Hoeveelheid</b></td>
            <td><b>Prijs</b></td>
            <td><b>Totaal</b></td>
        </tr>
    </thead>
    <tbody>
        @{
            decimal alles = 0;
            foreach(var order in Model.orders)
            {
                alles += order.Total;
                <form method="post">
                <input type="hidden" value="@order.Amount" name="Amount">
                <input type="hidden" value="@order.ProductId" name="ProductId">

                <tr>
                    <td>@order.Name</td>
                    <td>
                        <button class="btn btn-outline-dark btn-sm" asp-page-handler="Decrement">-</button>
                        <a style="margin: 5px">@order.Amount</a>
                        <button class="btn btn-outline-dark btn-sm" asp-page-handler="Increment">+</button>
                    </td>
                    <td>@order.Price</td>
                    <td>@order.Total</td>
                </tr>
                </form>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><b>@alles</b></td>
        </tr>
    </tfoot>
</table>

<a class="btn btn-primary" asp-area="" asp-page="/Rest/Alles betalen">Alles betalen</a>
<a class="btn btn-secondary" asp-area="" asp-page="/Rest/Per persoon betalen">Per persoon betalen</a>

WebdevProjectStarterTemplate/Pages/Rest/Per persoon betalen.cshtml
@page
@model WebdevProjectStarterTemplate.Pages.Rest.Per_persoon_betalenModel
@{
}
<h1><b>Per persoon betalen</b></h1>
<p>de geselecteerde tafel is <a style="font-weight: bold">@Model.RTableId</a></p>
<form method="post">
<table class="table table-striped">
    <thead>
        <tr>
            <td><b>product</b></td>
            <td><b>Aantal</b></td>
            <td><b>Prijs</b></td>
            <td><b>Totaal</b></td>
        </tr>
    </thead>
    <tbody>
            @{
                int iterator = 0;
                decimal alles = 0;
            foreach(var order in Model.orders)
            {
                var ProductName = "product[" + iterator + "]";
                var AmountName = "amount[" + iterator + "]";

                alles += order.Total;
                <tr>
                    <td>@order.Name</td>
                    <td>
                            <button type="button" class="btn btn-outline-dark" onclick="decrease('@order.Name')">-</button>
                            <a style="margin: 5px" class="@order.Name">0</a>
                            <button type="button" class="btn btn-outline-dark" onclick="increase('@order.Name')">+</button> van de @(@order.Amount - @order.AmountPaid)
                        <input type="hidden" value="0" class="@order.Name" name="@ProductName">
                        <input type="hidden" value="@order.ProductId" name="@AmountName">
                    </td>
                    <td>@order.Price</td>
                    <td>@order.Total</td>
                </tr>
                iterator++;
            }
            }

    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><b>@alles</b></td>
        </tr>
    </tfoot>
</table>
    <button class="btn btn-danger">Betaal</button>
</form>

<script>
    function increase(id){
        var elements = document.getElementsByClassName(id);
        for (var i = 0; i < elements.length; i=+2) {
            elements[i].innerHTML = Number(elements[i].innerHTML)+1;
            elements[i+1].value = Number(elements[i+1].value) + 1;
            //elements[i].style.display = "none";
        }
    }

    function decrease(id){
        var elements = document.getElementsByClassName(id);
        for (var i = 0; i < elements.length; i++) {
            elements[i].innerHTML = Number(elements[i].innerHTML)-1;
            elements[i+1].value = Number(elements[i+1].value) - 1;
        }
    }

</script>